const assert = require('assert');
const { buildLearnerProfile } = require('../../open-education-intelligence/learner-intelligence');
const { registerResource, findLearningResources } = require('../../open-education-intelligence/knowledge-intelligence');
const { buildLearningPath } = require('../../open-education-intelligence/learning-intelligence');
const { buildPracticeSet, assessmentBoundary } = require('../../open-education-intelligence/assessment-intelligence');
const { registerOpportunity, matchOpportunities } = require('../../open-education-intelligence/opportunity-intelligence');
const { createNounAdapter } = require('../../open-education-intelligence/adapters/noun-adapter');
const { routeInstitutionRequest } = require('../../open-education-intelligence/open-student-environment');
const learner = buildLearnerProfile({ id: 'l1', goals: ['data analyst'] });
const resource = registerResource({ id: 'r1', title: 'Data Basics', subject: 'data', licence: 'CC BY', provenance: { status: 'official' }, verification: { status: 'verified' } });
const resources = findLearningResources({ subject: 'data' }, { resources: [resource] });
const pathway = buildLearningPath('data analyst', learner, { nodes: [{ id: 'c1', type: 'Course', attributes: { goal: 'data analyst' } }], relationships: [] });
assert.equal(resources[0].resource.id, 'r1');
assert.equal(pathway.steps[0].id, 'c1');
assert.equal(buildPracticeSet({ id: 'p1' }).graded, false);
assert.equal(assessmentBoundary('complete-graded-work').allowed, false);
const opportunity = registerOpportunity({ id: 'o1', title: 'Data Internship', skills: ['analysis'], verification: { status: 'verified' } });
assert.equal(matchOpportunities({ skills: ['analysis'] }, [opportunity])[0].opportunity.id, 'o1');
const noun = createNounAdapter();
assert.equal(routeInstitutionRequest({ adapters: [noun] }, 'noun', { type: 'form_request' }).routed, true);
console.log('OEI end-to-end tests passed');
